# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Pump' do
pod 'AFNetworking', '2.2.1'
pod 'KLCPopup'
pod 'VENTokenField'
pod 'Venmo-iOS-SDK'
pod 'GoogleMaps'
pod 'SDWebImage', '~>3.7'
pod 'HMSegmentedControl'
pod 'BBBadgeBarButtonItem'
end

target 'PumpTests' do

end

