# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Pump' do
pod 'AFNetworking', '2.2.1'
pod 'VENTokenField'
pod 'Venmo-iOS-SDK'
pod 'GoogleMaps'
end

target 'PumpTests' do

end

